version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
